name: Scheuled Portal-E2E Pipeline
on:
  schedule:
    - cron: "30 22 * * *" # Daily 04:30 AM in midnight

# All Environments variables declared and set here.
env:
  TAG: "ci"
  MODULE: "All"
  SELF_AGENT: "self-agent"
  EXTERNAL_AGENT: "external-agent"

# Jobs for deploying and testing litmus-portal on a KinD Cluster
jobs:
  Kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setting up Main Cluster
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.9.0"
          name: ${{ env.SELF_AGENT }}

      - name: Configuring and Testing the Cluster Installation
        run: |
          kubectl cluster-info --context kind-${{ env.SELF_AGENT }}
          kubectl get nodes
          kubectl get pods -n kube-system

      - name: Deploying Litmus-Portal using **k8s-manifest**
        run: |
          chmod 755 ./litmus/install-portal.sh
          ./litmus/install-portal.sh
        env:
          PORTAL_VERSION: ${{ env.Tag }}
          LOAD_BALANCER: "false"

      - name: Setting up Agent Cluster
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.9.0"
          name: "${{ env.EXTERNAL_AGENT }}"

      - name: Configuring and Testing the Agent Installation
        run: |
          kubectl cluster-info --context kind-${{ env.EXTERNAL_AGENT }}
          kubectl get nodes
          kubectl get pods -n kube-system

      - name: Installing LitmusCTL on Agent Cluster
        run: |
          curl -O https://litmusctl-bucket.s3-eu-west-1.amazonaws.com/litmusctl-linux-amd64-master.tar.gz
          tar -zxvf litmusctl-linux-amd64-master.tar.gz
          chmod +x litmusctl
          sudo mv litmusctl /usr/local/bin/litmusctl
          litmusctl version

      - name: Running basic tests (Login and Onboarding Tests)
        uses: cypress-io/github-action@v2
        continue-on-error: false
        with:
          spec: cypress/integration/Basic_Setup/**/*.spec.js
          working-directory: Cypress/
          config-file: cypress.prod.json

      - name: Running Parallel tests
        uses: cypress-io/github-action@v2
        if: always()
        continue-on-error: true
        with:
          spec: cypress/integration/Parallel_Tests/**/*.spec.js
          working-directory: Cypress/
          config-file: cypress.prod.json

      - name: Registering External Agent in Cluster Mode
        if: always()
        run: |
          kubectl config use-context kind-${{ env.SELF_AGENT }}
          kubectl wait --for=condition=Ready pods --all --namespace litmus --timeout=120s
          kubectl config use-context kind-${{ env.EXTERNAL_AGENT }}
          sudo apt-get install expect
          chmod 755 litmus/litmusctl-register.sh
          litmus/litmusctl-register.sh "http://localhost:3001" 1

      - name: Portal Cleanup
        if: always()
        run: |
          chmod 755 ./litmus/uninstall-portal.sh
          ./litmus/uninstall-portal.sh
        env:
          PORTAL_VERSION: ${{ env.Tag }}

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: Cypress/cypress/screenshots

      - name: Deleting All kind clusters
        if: always()
        run: |
          kind delete cluster --name=${{ env.SELF_AGENT }}
          kind delete cluster --name=${{ env.EXTERNAL_AGENT }}
